# -*- coding: utf-8 -*-
"""session-1-tasks.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j7D_owmjwodnY8zedxdpIOQIyB-GufeU

# Task : Session 1
Solve these questions own your own and try to test yourself what you have learned in the session.

Happy Learning!

### Q1 :- Print the given strings as per stated format.

**Given strings**:
```
"Data" "Science" "Mentorship" "Program"
"By" "CampusX"
```
**Output**:
```
Data-Science-Mentorship-Program-started-By-CampusX
```

Concept- [Seperator and End]
"""

# Write your code here
words1 = ["Data", "Science", "Mentorship", "Program"]
words2 = ["By", "CampusX"]
result = "-".join(words1 + ["started"] + words2)
print(result)

"""### Q2:- Write a program that will convert celsius value to fahrenheit."""

# Write your code here
fehranheit = int(input("Enter the temperature : "))
celcius = (fehranheit-32) * 5/9
print(celcius)

"""### Q3:- Take 2 numbers as input from the user.Write a program to swap the numbers without using any special python syntax."""

# Write your code here
a = int(input())
b = int(input())
temp = a
a = b
b = temp
print(a , b)

"""### Q4:- Write a program to find the euclidean distance between two coordinates.Take both the coordinates from the user as input."""

# Write your code here
import numpy as np
x1 = int(input())
y1 = int(input())
x2 = int(input())
y2 = int(input())

a = (x2 - x1)*(x2 - x1)
b = (y2 - y1)*(y2 - y1)

eucl_dist = np.sqrt(a + b)
print(eucl_dist)

"""### Q5:- Write a program to find the simple interest when the value of principle,rate of interest and time period is provided by the user.

"""

# Write your code here
p = int(input())
r = int(input())
t = int(input())

SI = p*r*t/100

print(SI)

"""###
 Q6:- Write a program to find the sum of squares of first n natural numbers where n will be provided by the user.



"""

# Write your code here
import numpy as np
n = int(input())
sum = 0
for i in range(0,n+1,1) :
  x = np.square(i)
  sum = sum + x
print(sum)

"""### Q7:- Given the first 2 terms of an Arithmetic Series.Find the Nth term of the series. Assume all inputs are provided by the user."""

# Write your code here
n = int(input())
a1 = int(input())
a2 = int(input())
d = a2 - a1
Nth = a1 + (n-1)*d
print(Nth)

"""### Q8:- Given 2 fractions, find the sum of those 2 fractions.Take the numerator and denominator values of the fractions from the user."""

# Write your code here
a = int(input())
b = int(input())
c = int(input())
d = int(input())

ans = (a*d + b*c)/(b*d)
print(ans)

"""### Q9:- Given the height, width and breadth of a milk tank, you have to find out how many glasses of milk can be obtained? Assume all the inputs are provided by the user.



Input:<br>
Dimensions of the milk tank<br>
H = 20cm, L = 20cm, B = 20cm
<br><br>
Dimensions of the glass<br>
h = 3cm, r = 1cm
"""

# Write your code here
H = int(input())
L = int(input())
B = int(input())
h = int(input())
r = int(input())

tank_vol = H*L*B
glass_vol = 3.14*h*r*r

ans = tank_vol/glass_vol

print(ans)